language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: MbcahDwQidrfn8UIbeQSQu32phzb/f1U+0AaKTotzCMYx2jOIMq0ewh00M9FcHBy5vYCbY9b89+h0TvyfLllf1Cspk0qw1Z0osqvGop2Blob8+T/KEPH0LApPskcmiUtuxtwEaWSyW358YEK5gVJfQprC1BPyP5yWJffUpJARSBK6pd5prv1lcPW0DptBvIx5qCRUsd8ohl5KZmG2b0fG3KQ6nVabyi4ZyS5bdpkDNDVLM5F0BFQwJ1FMcGpDL4gF5PvSfOChvSMr+dZtk5SROvF9BNmsMQ6S7utAXwEFaxSkPb02al+NKsG0YsHl6/V4+QYBoqgZBH3F7GrXgHgYu6YF2+UY3qgqBJxEcmMbtft2NPlWb7WsKkK6YJP8brmWUOkOxY7mZxOUKA2te5SWB0QS4FlRWRB+jGPv1oK5laRdIHBvxaIvQJsYKj/0T92JzsbT36V858alqd4NND9X0d6+x/8QIj7fX83CYfcRzARUhblnDfQ/Ryr6O+TYgThvtXz38vkfIWFtdsMGdCU3pwNqcm3p02xhLv1DP3+KZfrQACRdDv09j8mGBImnyWSaZ54TSm7iP/wG0b43uPw9BK73yEAjLhd7P/YWvKjXeLO030XZ6G1toL2xDLMDoA8h/jfkQYtgsU1gIggAvbrMl9WYDJKqqhWBmFOrjdXt+g=
  on:
    tags: true
    repo: SpheMakh/simms
